/**
 * scripts/fetchSDE.mjs
 *
 * Pre-build script: downloads the official EVE Online Static Data Export,
 * extracts types.jsonl, and generates client/src/lib/shipTypes.ts.
 *
 * Data source: https://developers.eveonline.com/static-data
 * Automation URL: https://developers.eveonline.com/static-data/eve-online-static-data-latest-jsonl.zip
 *
 * Usage: node scripts/fetchSDE.mjs
 */

import { writeFileSync, createWriteStream, existsSync, unlinkSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createInterface } from 'readline';
import { Readable } from 'stream';
import AdmZip from 'adm-zip';

const __dirname = dirname(fileURLToPath(import.meta.url));

const SDE_ZIP_URL =
  'https://developers.eveonline.com/static-data/eve-online-static-data-latest-jsonl.zip';

const OUT_FILE    = resolve(__dirname, '../src/lib/shipTypes.ts');
const TMP_ZIP     = resolve(__dirname, '../../.sde-tmp.zip');

// Ship category ID in EVE SDE
const CATEGORY_SHIP = 6;

async function downloadZip(url, dest) {
  console.log('[fetchSDE] Downloading SDE zip from', url);
  const res = await fetch(url, { redirect: 'follow' });
  if (!res.ok) throw new Error(`HTTP ${res.status} downloading SDE`);

  const writer = createWriteStream(dest);
  const reader = Readable.fromWeb(res.body);
  await new Promise((resolve, reject) => {
    reader.pipe(writer);
    writer.on('finish', resolve);
    writer.on('error', reject);
    reader.on('error', reject);
  });
  console.log('[fetchSDE] Download complete.');
}

async function main() {
  try {
    await downloadZip(SDE_ZIP_URL, TMP_ZIP);

    console.log('[fetchSDE] Extracting types.jsonl...');
    const zip = new AdmZip(TMP_ZIP);
    const entry = zip.getEntry('types.jsonl');
    if (!entry) throw new Error('types.jsonl not found in SDE zip');

    const jsonlContent = entry.getData().toString('utf8');
    const lines = jsonlContent.split('\n').filter((l) => l.trim());

    console.log(`[fetchSDE] Parsing ${lines.length} type records...`);

    const entries = [];
    for (const line of lines) {
      let record;
      try {
        record = JSON.parse(line);
      } catch {
        continue;
      }

      // SDE JSONL format uses _key for integer-keyed dictionaries
      const typeId   = record._key ?? record.typeID;
      const name     = record.name?.en ?? record.name ?? null;
      const groupId  = record.groupID ?? record.group_id ?? null;
      const catId    = record.categoryID ?? record.category_id ?? null;
      const published = record.published ?? true;

      if (!typeId || !name || !groupId || catId !== CATEGORY_SHIP || !published) continue;

      entries.push([typeId, { name: String(name), groupId: Number(groupId) }]);
    }

    console.log(`[fetchSDE] Found ${entries.length} published ship types. Writing ${OUT_FILE}...`);

    const bodyLines = entries
      .map(([id, { name, groupId }]) => {
        const safeName = name.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
        return `  [${id}, { name: '${safeName}', groupId: ${groupId} }],`;
      })
      .join('\n');

    const content = `/**
 * shipTypes.ts — AUTO-GENERATED by scripts/fetchSDE.mjs
 * Source: EVE Online Static Data Export (developers.eveonline.com/static-data)
 * Do not edit by hand.
 */

export interface ShipType {
  name:    string;
  groupId: number;
}

// @generated
const SHIP_TYPES_DATA: [number, ShipType][] = [
${bodyLines}
];

export const shipTypes: ReadonlyMap<number, ShipType> = new Map(SHIP_TYPES_DATA);
`;

    writeFileSync(OUT_FILE, content, 'utf8');
    console.log('[fetchSDE] Done.');
  } finally {
    if (existsSync(TMP_ZIP)) unlinkSync(TMP_ZIP);
  }
}

main().catch((err) => {
  console.error('[fetchSDE] Fatal error:', err);
  process.exit(1);
});
