/**
 * scripts/fetchSDE.mjs
 *
 * Pre-build script: downloads the EVE SDE ship type data from Fuzzwork
 * and generates client/src/lib/shipTypes.ts.
 *
 * Usage: node scripts/fetchSDE.mjs
 */

import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const FUZZWORK_CSV =
  'https://www.fuzzwork.co.uk/dump/latest/invTypes.csv.bz2';

// Alternative: ESI SDE endpoint (simpler, no bzip2 decompression needed)
const ESI_TYPES_URL = 'https://esi.evetech.net/v1/universe/types/?page=';

const OUT_FILE = resolve(__dirname, '../src/lib/shipTypes.ts');

// Ship category IDs that correspond to ships (6 = Ships)
const CATEGORY_SHIP = 6;

async function fetchAllTypeIds() {
  const page1Res = await fetch(`${ESI_TYPES_URL}1`);
  const totalPages = parseInt(page1Res.headers.get('X-Pages') ?? '1', 10);
  const page1 = await page1Res.json();

  const allIds = [...page1];
  const pages = [];
  for (let p = 2; p <= Math.min(totalPages, 50); p++) {
    pages.push(p);
  }

  const chunks = [];
  // Fetch in batches of 5 concurrent requests
  while (pages.length) {
    const batch = pages.splice(0, 5);
    const results = await Promise.all(
      batch.map((p) =>
        fetch(`${ESI_TYPES_URL}${p}`)
          .then((r) => r.json())
          .catch(() => []),
      ),
    );
    for (const r of results) allIds.push(...r);
  }
  return allIds;
}

async function fetchTypeInfo(typeId) {
  const res = await fetch(
    `https://esi.evetech.net/v3/universe/types/${typeId}/?language=en`,
  );
  if (!res.ok) return null;
  return res.json();
}

async function main() {
  console.log('[fetchSDE] Fetching all type IDs from ESI...');
  let allIds;
  try {
    allIds = await fetchAllTypeIds();
  } catch (err) {
    console.warn('[fetchSDE] ESI fetch failed, keeping existing shipTypes.ts:', err.message);
    return;
  }

  console.log(`[fetchSDE] Total type IDs: ${allIds.length}. Filtering ships...`);

  const entries = [];
  let processed = 0;

  // Process in batches to avoid hammering ESI
  const BATCH = 20;
  for (let i = 0; i < allIds.length; i += BATCH) {
    const batch = allIds.slice(i, i + BATCH);
    const results = await Promise.all(batch.map((id) => fetchTypeInfo(id).catch(() => null)));
    for (const info of results) {
      if (!info) continue;
      if (info.category_id !== CATEGORY_SHIP) continue;
      entries.push([info.type_id, { name: info.name, groupId: info.group_id }]);
    }
    processed += batch.length;
    if (processed % 1000 === 0) console.log(`[fetchSDE]  ${processed}/${allIds.length}`);
  }

  console.log(`[fetchSDE] Found ${entries.length} ship types. Writing ${OUT_FILE}...`);

  const lines = entries
    .map(([id, { name, groupId }]) => {
      const safeName = name.replace(/'/g, "\\'");
      return `  [${id}, { name: '${safeName}', groupId: ${groupId} }],`;
    })
    .join('\n');

  const content = `/**
 * shipTypes.ts — AUTO-GENERATED by scripts/fetchSDE.mjs
 * Do not edit by hand.
 */

export interface ShipType {
  name:    string;
  groupId: number;
}

// @generated
const SHIP_TYPES_DATA: [number, ShipType][] = [
${lines}
];

export const shipTypes: ReadonlyMap<number, ShipType> = new Map(SHIP_TYPES_DATA);
`;

  writeFileSync(OUT_FILE, content, 'utf8');
  console.log('[fetchSDE] Done.');
}

main().catch((err) => {
  console.error('[fetchSDE] Fatal error:', err);
  process.exit(1);
});
